services:
  postgres:
    container_name: postgres_touristic_container
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=touristicagency'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - touristicagency-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  touristicagency-data: