spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/touristicagency
  jpa:
    show-sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true
